name: Python 3.10.4, PostgreSQL, and Database Setup

on:
  push: {}

jobs:
  setup-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python 3.10.4
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.4'

      - name: Install PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install postgresql postgresql-contrib -y  # Install PostgreSQL and additional packages

      - name: Create Database 
        run: |
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}

          sudo -u postgres psql -c "CREATE DATABASE ${DB_NAME}"
          sudo -u postgres psql -c "CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASSWORD}'"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER}"

          echo "Database '${DB_NAME}' created successfully."
